### ISSUE TITLE
`KeysClaimRequest` generates malformed bodies

### ISSUE THREAD

**Issue by richvdh** [matrix-org/matrix-rust-sdk-crypto-wasm#56]
The `body` of `KeysClaimRequest` structs looks like this:

```json
{"one_time_keys":{"@richvdh:matrix.org":{"IUYUDKWEMN":"signed_curve25519"}},"timeout":{"nanos":0,"secs":10}}
```

That `timeout` property is malformed according to the [spec](https://spec.matrix.org/v1.8/client-server-api/#post_matrixclientv3keysclaim)

**Comment by richvdh** [comment]
This is something of a replay of https://github.com/matrix-org/matrix-rust-sdk/issues/801, but in different bindings. It seems a bit silly to me if we have to remember to fix this every time we create bindings.

@Hywan as the author of the magical `request!` macro that generates the `body`: could we just use the JSON serialisation of ruma's `KeysClaimRequest` struct (which appears to have code to deal with this case already) rather than building the body ourselves?

**Comment by Hywan** [comment]
Yes, the idea is basically to re-apply https://github.com/matrix-org/matrix-rust-sdk/pull/817/ I suppose.

**Comment by richvdh** [comment]
> Yes, the idea is basically to re-apply https://github.com/matrix-org/matrix-rust-sdk/pull/817 I suppose.

It seems silly to me that each set of bindings has to know which fields are `Duration`s and manually convert them, when the fields in the Ruma structure already have `serde` annotations (https://docs.rs/ruma-client-api/0.13.0/src/ruma_client_api/keys/claim_keys.rs.html#31-35). Can we not take advantage of that somehow?
